name: Cleanup releases

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - build: NoblePup32
    steps:
      - name: Delete old ${{ matrix.build }} releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          delete_tag_pattern: ${{ matrix.build }}
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
