name: Cleanup releases

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - build: NoblePup32
    steps:
      - name: Delete old ${{ matrix.build }} releases
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: ${{ matrix.build }}/release-
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
