name: Cleanup releases

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - build: BookwormPup32
          - build: BookwormPup64
          - build: BionicPup32
          - build: FocalPup32
          - build: JammyPup32
          - build: NoblePup32
          - build: S15Pup32
          - build: S15Pup64
          - build: VoidPup32
          - build: VoidPup64
    steps:
      - name: Delete old ${{ matrix.build }} releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          delete_tag_pattern: ${{ matrix.build }}
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
