name: TrixiePup32-Retro

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  x86:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      name: 'TrixiePup32Retro'
      version: '2508'
      arch: x86
      compat-distro: debian
      compat-distro-version: dpupt32
      kernel: 'debian-bookworm'
      prefix: dpupt32
      artifact: TrixiePup32-Retro-${{ github.run_number }}
      retention: 1

  upload32:
    needs: x86
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: TrixiePup32-Retro-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv dpupt32-2508.iso TrixiePup32-Retro-2508-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: TrixiePup32-Retro-2508
          tag_name: TrixiePup32-Retro/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
