name: DPupT64Wayland

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  x86_64:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      runner: ubuntu-22.04
      name: 'TrixiePup64Wayland'
      version: '2510'
      arch: x86_64
      compat-distro: debian
      compat-distro-version: dpupt64wayland
      kernel: 'debian-trixie'
      prefix: dpupt64w
      artifact: TrixiePup64Wayland-${{ github.run_number }}
      retention: 1

  upload64:
    needs: x86_64
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: TrixiePup64Wayland-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv dpupt64w-2510.iso TrixiePup64-Wayland-2510-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: TrixiePup64-Wayland-2510
          tag_name: BookwormPup64-ghtest/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
