name: dpupbw64

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  x86_64:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      runner: ubuntu-22.04
      name: 'BookwormPup64'
      version: '10.0.11'
      arch: x86_64
      compat-distro: debian
      compat-distro-version: dpupbw64
      kernel: 'debian-bookworm'
      prefix: dpupbw64
      artifact: BookwormPup64-${{ github.run_number }}
      retention: 1

  upload64:
    needs: x86_64
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: BookwormPup64-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv dpupbw64-10.0.11.iso BookwormPup64-ghtest-10.0.11-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: BookwormPup64-ghtest-10.0.11
          tag_name: BookwormPup64-ghtest/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
