name: s15pup

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  x86_64:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      name: 'S15Pup64'
      version: '22.12'
      arch: x86_64
      compat-distro: slackware64
      compat-distro-version: s15pup64
      kernel: '5.15.x'
      prefix: s15pup64
      artifact: S15Pup64-${{ github.run_number }}
      retention: 1

  x86:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      name: 'S15Pup32'
      version: '22.12'
      arch: x86
      compat-distro: slackware
      compat-distro-version: s15pup32
      kernel: '5.10.x'
      prefix: s15pup32
      artifact: S15Pup32-${{ github.run_number }}
      retention: 1

  upload64:
    needs: x86_64
    runs-on: ubuntu-20.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: S15Pup64-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv s15pup64-22.12.iso S15Pup64-22.12-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: S15Pup64-22.12
          tag_name: S15Pup64/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt

  upload32:
    needs: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: S15Pup32-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv s15pup32-22.12.iso S15Pup32-22.12-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: S15Pup32-22.12
          tag_name: S15Pup32/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
