name: upup32-nn

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  unn:
    uses: peabee/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: peabee/woof-CE
      ref: testing
      name: 'NoblePup32'
      version: '24.04'
      arch: x86
      compat-distro: ubuntu
      compat-distro-version: upupnn+d
      kernel: '6.6.x'
      prefix: upupnn+bw
      artifact: NoblePup32-${{ github.run_number }}
      retention: 1

  uploadnn:
    needs: unn
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: NoblePup32-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv upupnn+bw-24.04.iso NoblePup32-24.04-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: NoblePup32-24.04
          tag_name: NoblePup32/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
